language: cpp
sudo: required
dist: xenial
services:
    - xvfb
branches:
  only:
    - master
addons:
  apt:
    sources:
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial multiverse"
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe"
    packages:
    - cmake
    - libxaw7-dev
    - libzzip-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libxt-dev
    - libgles2-mesa-dev
    - mesa-common-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev # legacy GL RenderSystem only
    - python3-dev
    - python3-lxml     # for validate script
    - nvidia-cg-dev
    - libpugixml-dev
    - swig3.0
    - mono-mcs
before_script:
    - if [ "$TRAVIS_OS_NAME" =   "osx" ]; then brew update && brew install freetype libzzip sdl2 pugixml ; fi
osx_image: xcode8.3
env:
    - TEST=TRUE
    - GL3ES=TRUE # build GL3Plus and GLES2 Rendersystems
    - ANDROID=TRUE
    - IOS=TRUE
compiler:
    - clang
    - gcc
matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: linux
          env: IOS=TRUE
        - os: linux
          env: GL3ES=TRUE
        - os: osx
          compiler: gcc
        - os: osx
          env: TEST=TRUE
        - os: osx
          env: ANDROID=TRUE
script:
    - cmake -P ci-build.cmake
    - BUILD_CMD="cmake --build build"
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then BUILD_CMD="$BUILD_CMD -- -k -j 2" ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then BUILD_CMD="set -o pipefail && $BUILD_CMD | xcpretty" ; fi
    - echo $BUILD_CMD && eval $BUILD_CMD
    # run unit tests
    - if [ $TEST ]; then build/bin/Test_Ogre ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" -a "$IOS" != "TRUE" ]; then build/bin/Debug/Test_Ogre.app/Contents/MacOS/Test_Ogre ; fi
    # XMLConverter works & validates
    - if [ $TEST ]; then build/bin/OgreXMLConverter Samples/Media/models/jaiqua.mesh && build/bin/OgreXMLConverter Samples/Media/models/jaiqua.skeleton ; fi
    - if [ $TEST ]; then python3 Tools/XMLConverter/docs/validate.py Samples/Media/models/jaiqua.mesh.xml ; fi
    # run visual tests
    - if [ $TEST ]; then cd build/bin && ./TestContext -rs "OpenGL Rendering Subsystem" ; fi
    # verify that the python modules are loadable
    - if [ $TEST ]; then cd ../lib && python -c "import _Ogre; import _RTShader" ; fi
    # whitespace sanity
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git diff --check ${TRAVIS_COMMIT_RANGE/.../..} ; fi
os:
    - linux
    - osx
cache: apt
before_deploy:
    - if [ $ANDROID ]; then cd build/OgreJNI && zip -qr ogre-sdk-android-arm64-v8a.zip * ; fi
deploy:
  - provider: bintray
    key:
      secure: "kTzm4IUxRX3gBMCS/8hV1PKNqsb6tJHGjroteXQZL2kH8WPFQqjse08ecj/aLbCDTVYTyOfIj+af+CuJTwVOfxdIrZdwUj+ARmJMWrqCV8MYDSuzLEtIqZfInxqMBG3WKJIjj+NDkLQzYcgptOdyuZKQ/fNvZvLAvy6xFQqEfXIiYOl/RPZQw0nHP94ltZ/XrsX81hLk+EB+GFrxkHqvd7jRYjwl0Rd4PPbsriOf2BtZbUZhQqQ4dG8F/ETVFh4PyemFp2OFEKzHfN2cFDJOeQgYhxLU6BRAwQilC+35kzWuEEPfsErfKk2Cda1/by73VS7no1A9AiHQdteE4udzBpGJ+LSxlXLpF20wDC074/VrM7xGPY74BKwLBi53PZZxgTmuvoZvrDCbKZ0S5pclhR+uUidjMndkevvQG7Va+i5qIViVIkFOc5BWP0zErt/oKqQOGC6xlEjhBRNA2ZORTiwXv+ndAPltdq1a56c9vqfwXN7gTm/TXl/XAUu23tSJj3fHITZ0akyayjvpVv3B20mDaZQXOy6OXkUBcy69sUfv09/tDdbuI8XoGQJLsax/uWiYdZP03/5UwsT6SISCNfjsahGY9A+R/ORQ9RpgUcnbnQdIQ5Qc8WONKriBR2N2/DeYDXdDfynWUgN9fuk5NOzEolk3ZHkzTDGq9kjqM94="
    user: paroj
    skip_cleanup: true
    file: $TRAVIS_BUILD_DIR/Other/bintray.json
    on:
      condition: $ANDROID
