platform: x64
configuration: Release
image:
 - Visual Studio 2017
 - Visual Studio 2013
install:
 - cmd: choco install swig -y --version 3.0.12 & exit 0
 - cmd: cd %APPVEYOR_BUILD_FOLDER%
 - cmd: git submodule update --init --recursive
build_script:
 - cmake -P ci-build.cmake
 - cmake --build build --config Release --target INSTALL
test_script:
 - set PATH=%PATH%;build\gtest\lib
 - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" build\bin\release\Test_Ogre.exe --gtest_filter=-MeshWithoutIndexDataTests*
cache:
- ogredeps -> CMake/Dependencies.cmake
branches:
  only:
    - master
    - stable
artifacts:
  - path: build/sdk
    name: ogre-sdk-1.12.5-vc15-x64
deploy:
- provider: BinTray
  username: paroj
  api_key:
    secure: 4nFEwKApbHUf7UajsDt6Z7QOl3zzgEz6YbWGSGx5AiPxozWEQHEyGc6c9xE7utWE
  subject: ogrecave
  repo: ogre
  package: ogre-sdk-vc15-x64
  publish: true
  override: true
  version: 1.12.5
  on:
    branch: master
    APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
